// next imports
import Head from "next/head";
import { useRouter } from "next/router";

// font
import { Inter } from "next/font/google";

// interface
import LevelDataClass from "@/common/interfaces/LevelDataClass";

// swr
import useSWR from "swr";
import { fetcher } from "@/common/lib/fetcher";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { data, error, isLoading } = useSWR("/api/get_all_levels", fetcher);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mx-auto ${inter.className}`}>
        <br />
        <div className="flex flex-col divide-y">
          {data === undefined && <div>Loading...</div>}

          {!isLoading &&
            data !== undefined &&
            data?.map((level: LevelDataClass) => {
              return (
                <div
                  key={level.id}
                  className="bg-blue-900 p-5 cursor-pointer hover:bg-blue-800 transition-colors"
                  onClick={() => {
                    router.push(`/level/${level.id}`);
                  }}
                >
                  <h1>{level.title}</h1>
                </div>
              );
            })}
        </div>
      </main>
    </>
  );
}
