// next imports
import Head from "next/head";
import { useRouter } from "next/router";

// font
import { Inter } from "next/font/google";

// fs and path
import fs from "fs";
import path from "path";

// interface
import LevelDataClass from "@/common/interfaces/LevelDataClass";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ levelData }: { levelData: LevelDataClass[] }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mx-auto ${inter.className}`}>
        <br />
        <div className="flex flex-col divide-y">
          {levelData.map((level: LevelDataClass) => {
            return (
              <div
                key={level.id}
                className="bg-blue-900 p-5 cursor-pointer hover:bg-blue-800 transition-colors"
                onClick={() => {
                  router.push(`/level/${level.id}`);
                }}
              >
                <h1>{level.title}</h1>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  // get all the folders in levels
  const levels = fs.readdirSync(path.join(process.cwd(), "levels"));

  // foreach of the levels, get the level data
  let levelData = levels.map((level) => {
    const levelData = fs.readFileSync(
      path.join(process.cwd(), "levels", level, "data.json"),
      "utf-8"
    );
    return JSON.parse(levelData);
  });

  return {
    props: {
      levelData,
    },
  };
};
